#
# File System Modules (for PlayStation 2)
# Copyright (C) Konami Computer Entertainment Japan
# Codebase Restoration by Joy Division
#

all:\
	cdbios cdbios_ee \
	hdbios hdbios_ee \
	filesys

cdbios cdbios_ee:
	$(MAKE) -f$@.mk

hdbios hdbios_ee:
	@echo "Skipping $@ (PLACEHOLDER)"

filesys:
	$(MAKE) -f$@.mk
