/*----------------------------------------------------------------------*/
libmain.c
	sif_set_callback_func
	sif_send_packet_and_data
	i_sif_send_packet_and_data
	sif_send_direct
	i_sif_send_direct
	i_sif_send_mem
	sif_send_mem
	sif_check_status
	sif_init
	KCEJ_sifman_init
	gcc2_compiled.
	__gnu_compiled_c
	cmdpacket
	init_flag
/*----------------------------------------------------------------------*/
rvman.c
	rv_man_callback
	sif_init_rv_man
	sif_rv_get_queue
	sif_rv_call_func
	sif_rv_return_value
	i_sif_rv_return_value
	sif_rv_release_queue
	sif_get_mem
	gcc2_compiled.
	__gnu_compiled_c
	init_flag
	SIF_RV_Queue
	SIF_RV_Queue_id
/*----------------------------------------------------------------------*/
__tmp.s
	_retonly
/*----------------------------------------------------------------------*/
/tmp/ccTxrkHE_ilb_stub.s
/*----------------------------------------------------------------------*/
.text
.init
.fini
.data
.rodata
.sdata
.sbss
.bss
sifcmd_buffer
KCEJ_sifman_init
sceSifAddCmdHandler
sif_send_mem
printf
CpuResumeIntr
sif_rv_return_value
sceSifSetCmdBuffer
i_sif_rv_return_value
sif_check_status
sifcmd_stub
sif_rv_call_func
isceSifSendCmd
sif_send_packet_and_data
sif_init_rv_man
jsifman_entry
i_sif_send_packet_and_data
loadcore_stub
sif_set_callback_func
sceSifSetDma
callback_set_flag
RegisterLibraryEntries
sceSifDmaStat
CpuSuspendIntr
Module
stdio_stub
sifman_stub
sif_send_direct
sceSifSendCmd
Kprintf
sif_get_mem
sceSifInitCmd
intrman_stub
sif_rv_release_queue
i_sif_send_mem
sysmem_stub
sif_rv_get_queue
sif_init
i_sif_send_direct
